export const appServers = {
  serverConfig: [
    {
      area: "ut",
      nameServer: "NS2",
      port: 5162,
      servers: ["astrading-ut", "asacor-ut", "aspricing-ut"],
      defaultServer: "astrading-ut",
    },
    {
      area: "ut2",
      nameServer: "NS2",
      port: 5162,
      servers: ["astrading-ut2", "asacor-ut2", "asfxtrading-ut2"],
      defaultServer: "astrading-ut2",
    },
    {
      area: "dev",
      nameServer: "NS2",
      port: 5162,
      servers: ["asacor-dev", "asfrk-dev", "asinvops-dev", "aspricing-dev"],
      defaultServer: "aspricing-dev",
    },
    {
      area: "gpp",
      nameServer: "NS2",
      port: 5162,
      servers: ["astrading-gpp"],
      defaultServer: "astrading-gpp",
    },
    {
      area: "sp1",
      nameServer: "NS2",
      port: 5162,
      servers: [
        "astrading-sp1",
        "asbrazil102-sp1",
        "asfxtrading-sp1",
        "stp-sp1",
      ],
      defaultServer: "stp-sp1",
    },
    {
      area: "sp4",
      nameServer: "NS1",
      port: 5167,
      servers: ["appsvr-sp4"],
      defaultServer: "appsvr-sp4",
    },
    {
      area: "sp4",
      nameServer: "NS2",
      port: 5162,
      servers: ["astrading-sp4"],
      defaultServer: "astrading-sp4",
    },
    {
      area: "sp5",
      nameServer: "NS2",
      port: 5162,
      servers: ["astrading-sp5"],
      defaultServer: "astrading-sp5",
    },
    {
      area: "sp6",
      nameServer: "NS1",
      port: 5167,
      servers: ["appsvr-sp6", "astrading-sp6", "asacor-sp6"],
      defaultServer: "appsvr-sp6",
    },
    {
      area: "sp6",
      nameServer: "NS2",
      port: 5162,
      servers: ["asfxtrading-sp6"],
      defaultServer: "asfxtrading-sp6",
    },
    {
      area: "sp7",
      nameServer: "NS2",
      port: 5162,
      servers: ["aspricing-sp7"],
      defaultServer: "aspricing-sp7",
    },
    {
      area: "sp8",
      nameServer: "NS1",
      port: 5167,
      servers: ["appsvr-sp8", "appsvrdbg-sp8"],
      defaultServer: "appsvr-sp8",
    },
    {
      area: "sp8",
      nameServer: "NS2",
      port: 5162,
      servers: ["astrading-sp8", "asfxtrading-sp8"],
      defaultServer: "astrading-sp8",
    },
  ],
};
